blog 2
Nxtra/blogs-david-en-nick pull request #4
Opened 2020-11-12 09:40 UTC by Nxtra

2020-11-13 15:43 UTC, MrMomster requested changes
I did an initial review, did have time to go over it entirely.
Feel free to address my comment in the way you like. 

It's an interesting post, looking forward to reading the rest of it.

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +Let's explore the differences between these services.
AWS Kinesis Firehose and AWS Kinesis Data Streams offer a similar yet different streaming solution to transport and transform your data.

Let's explore the differences between these services.

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +Let's explore the differences between these services.
In the last part, you already mentioned that you would discuss the solutions and why you decided to use one.

- Is this part then relevant?

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +#### Kinesis Data Streams Properties
Link to the service FAQ?

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +- Can be digested with a Lambda function.
- Millisecond latency: used for real-time analytics and actions.
- Order is preserved per shard.
- Not completely serverless: you have to manage the number of shards yourself.
- Secure, durable storage of events on the stream up to 7 days.
- Can be digested with a Lambda function.

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +> Data Streams are for milliseconds realtime analytics.
> Data Streams are for milliseconds real-time analytics.
> You have to manage the shards yourself, which you can automate by using the Streams API.

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +You can find more info [here](https://aws.amazon.com/kinesis/data-streams/faqs/#:~:text=Shard%20is%20the%20base%20throughput,you%20create%20a%20data%20stream).
The latter means that when using a Kinesis data stream, we are responsible for provisioning enough capacity on our stream via the provisioning of shards.

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +Since the current use case is to ingest the data, then convert it to the "parquet" format and finally to land it on an S3 bucket for further batch processing, Kinesis Firehose is the service whose pr
The current use case is to ingest the data and then convert it to the "parquet" format. Finally, to land it on an S3 bucket for further batch processing, Kinesis Firehose is the service whose properties are best suited.

2020-11-13 15:43 UTC, MrMomster commented on skeleton.md
> +This will result in reduced costs when the data is queried for further batch processing.
Two primary considerations led to using the Parquet file format, a columnar data storage format, for storing the data on S3.
		
Firstly, the Parquet format provides efficient data compression, leading to a reduction of the required storage.
This added benefit will become more noticeable as the amount of data to be stored increases. 

Secondly, this format is optimized for query performance, which means that the amount of data being scanned during querying will be significantly less (compared to querying data in, e.g., the JSON format), which will result in reduced costs when the data is queried for further batch processing.

- Some references to back up the claims, I think it's a bit vague

2020-11-16 10:08 UTC, Nxtra commented on skeleton.md
> +Let's explore the differences between these services.
"Let's explore the differences between these services. " -> It is indeed a bit of a repeat. This sentence is there to guide the reader more naturally through the post instead of only making enumerations.

2020-11-16 10:09 UTC, Nxtra commented on skeleton.md
> +#### Kinesis Data Streams Properties
Good suggestion!

2020-11-16 10:28 UTC, Nxtra commented on skeleton.md
> +This will result in reduced costs when the data is queried for further batch processing.
> I did an initial review, did have time to go over it entirely.
> Feel free to address my comment in the way you like.
> 
> It's an interesting post, looking forward to reading the rest of it.
> I find pr's hard to review so I just copied the entire text and made the adjustments I felt necessary.
> 
> p.s. It's Mitch from Cloudway ;) Hope you are doing fine @Nxtra! :)

Hi Mr Momster,

Thanks for the review!
It's unfortunate that I left Cloudway so soon and without properly saying goodbye with all the covid stuff going on.

We will take up your review.

Here is everything fine. Hopefully you managed to steer clear of the COVID virus too!

2020-12-02 07:23 UTC, merged